name: Lint Ansible

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install `python`
        run: sudo apt-get update && sudo apt-get install -y python3.10 python3-pip
        shell: bash

      - name: Install `ansible-lint`
        run: python -m pip install ansible-lint
        shell: bash

      - name: Run `ansible-lint`
        run: ansible-lint
        shell: bash
